/*
 * Username : hasankartal
 * Password : mugiwaraluffy20Ace
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * Answer : 4613732
 * 4000000 rakamı geçilmeyecek.
 * Even-valued terms 2 ye tam bölünenilen sayılar demek
*/
public class Main {

    public static void main(String[] args) {
        int firstNumber = 1;
        int secondNumber = 2;
        int sum = 0;

        while(secondNumber <= 4000000) {
            if (secondNumber % 2 == 0) {
                sum += secondNumber;    //SecondNumber alttaki satırlarda değişeceği için bu satırda sum'a eklenir.
            }
            int temp = firstNumber;
            firstNumber = secondNumber;
            secondNumber += temp;
        }
        System.out.println("Toplam :" + sum);
    }
}
